import RegisterForm from '@/app/home/(auth)/register/register-form'
import Link from 'next/link'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Đăng ký tài khoản | REX Shop',
  description: 'Generated by create next app',
}

const RegisterPage = () => {
  return (
    <div className="flex flex-col items-center justify-center w-full p-6">
      <div className="rounded-lg dark:border-gray-700 shadow dark:border p-10 w-4/12">
        <h1 className="text-xl font-semibold text-center">Đăng nhập</h1>
        <div className="flex justify-center px-5 py-2.5">
          <RegisterForm />
        </div>
        <p className="text-sm font-light text-gray-500 dark:text-gray-400 flex justify-center">
        I agree with Phone Terms of Service, Privacy Policy, and default Notification Settings.
          
        </p>
      </div>
    </div>
  )
}

export default RegisterPage